### PR TITLE
Tictactoe example (React tutorial and ergnonomics)

### PR DESCRIPTION
**Pull request by alilee**
Hi guys, this is my attempt to port the React [tutorial](https://reactjs.org/tutorial/tutorial.html) to learn valerie and help compare with other frameworks. I'm not particularly hoping you'll merge this. If it is of use at all, it might make sense to be on another branch..

It will at least expose to you how a noob approaches the interface and (whether it is me or valerie) it highlights some opportunities for streamlining.

I have come from [fulcro](https://github.com/fulcrologic/fulcro) (a Clojure framework) which is spiritually aligned to Redux. All components query an normalised static database for their state.

I think it would be optimal to have a pure rust model in a store/state structure against which MV's can subscribe to changes. I'm very keen to discus this idea if you are interested.

### CODE REVIEW

**Comment by emmanuelantony2000** [comment]
That's pretty cool. I checked it out, works perfectly for me.
Sure we can discuss the store/state structure, in more detail.

**Comment by alilee** [comment]
Great! So here is my [sketch](https://github.com/alilee/valerie/tree/sketch/examples/tictactoe/src).

 It compiles but doesn't run (I didn't do the Node integration because you know that well already) and I can already think of many improvements (reducer, dispatch).

I would be very interested in your thoughts.

**Comment by davnav** [comment]
> Great! So here is my [sketch](https://github.com/alilee/valerie/tree/sketch/examples/tictactoe/src).
> 
> It compiles but doesn't run (I didn't do the Node integration because you know that well already) and I can already think of many improvements (reducer, dispatch).
> 
> I would be very interested in your thoughts.

awesome. I just played. I never knew that Valerie is already  ready for cool games.!

**Comment by alilee** [comment]
Ok guys, I think I am on to something very big here and would love to know your reaction. It is the ultimate of Redux and Svelte, with the typed power of Rust, courtesy of your great groundwork. 

The current [sketch works](https://github.com/alilee/valerie/tree/sketch/examples/tictactoe/src) and uses a mutator to change the state, which is reactive and updates through Node.

You should read the model and easily understand how the game is modelled in rust. I think it is completed decoupled from the MV/V.

Then read the lib and see how simple and clear the model-view is.

**Comment by emmanuelantony2000** [comment]
This is awesome @alilee .

Like how do propose to integrate the store/state structure part, in the lib itself?

(A trait might be a way to go, but wanted to know more takes on this)

**Comment by alilee** [comment]
This is how I am thinking about it at the moment (you probably have greater clarity than me on transition and motion):

[](https://postimg.cc/yWKhwrz9)

I think the statics-with-traits is a pretty good match for this problem, and is necessary for de-couple M from MV/V. Strict typing is enough of a protection though.

It would be better if the singleton and relation had more shared code, and if there was a way to parameterise the HashMap (eg. ```impl StoreDictionary for HashMap {}```).

**Comment by emmanuelantony2000** [comment]
That's great.

It would require rewrites to most parts of the lib, I'll try coming up with a basic implementation of it, to see how it works out.

**Comment by alilee** [comment]
What about a branch in your repo?

I'll put some stuff in there around fetch and more thoughts about store and form. I think you need the Atomics from state as component local state. My static should be "store"  and linked to fetch. What is wrong with Tag/Node? - it is a work of art!

I am not sure where routing goes - did you already have plans for that?

Also, what do you guys think about a more opinionated framework, which works with coupled backend? eg. client can safely generate new ids because all ids are uuids.

**Comment by emmanuelantony2000** [comment]
I created a new branch `state-feature`.

Could you edit the pull request to that branch?

**Comment by alilee** [comment]
If you commit this now, it will just commit the tictactoe example which uses the original valerie-state. It would be good to have this as a comparison point. Once you've committed I will open a pull request to put the store-sketch in. I have done some more work on fetch to show.

My rust is not very deep and it's possible I might be overusing associated methods...

**Pull request merged**
